# Generated by Django 2.2.7 on 2019-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerid', models.IntegerField()),
                ('buyerid', models.IntegerField()),
                ('bookid', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=100)),
                ('transaction_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
