# Generated by Django 2.2.7 on 2019-12-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bname', models.CharField(max_length=100)),
                ('bookowner', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='bphoto')),
                ('condition', models.CharField(max_length=100)),
                ('actual_price', models.IntegerField(blank=True, null=True)),
                ('selling_price', models.IntegerField(blank=True, null=True)),
                ('publication', models.CharField(max_length=100)),
                ('display_selling_price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='available', max_length=100)),
                ('uploaddate', models.DateField(auto_now_add=True)),
                ('solddate', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('buyerid', models.IntegerField(blank=True, null=True)),
                ('donation', models.BooleanField(default=False)),
            ],
        ),
    ]
